#!/bin/bash
#PATH="$PATH":$1//GitHub/Pod/Java pod template OSX/VM/install-vm
platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
   sudo apt-get install openjdk-8-jdk
   sudo apt-get install nmap
fi
elif [[ "$unamestr" == 'MacOS'||'OSX' ]]; then
  platform='MacOS'
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew install openssl
  check=xcode-select -p
  if [[$check==2]]; then
  xcode-select --install
   fi
  cd ~/Downloads
  curl -O http://ftp.gnu.org/gnu/wget/wget-1.15.tar.gz
  tar xvzf wget-1.15.tar.gz
  cd wget-1.15/
  ./configure --with-ssl=openssl
  make
  sudo make install
  brew install nmap
  brew update
  brew cask install java
fi
echo '$platform'
./VM/install-vm
