#!/bin/bash

platform='unknown'
unamestr=$OSTYPE
if [[ "$unamestr" == 'Linux' ]]; then
    sudo apt-get install wget
    
    
    elif [[ "$unamestr" == 'MacOS' ]] || [[ "$unamestr" == 'OSX' ]] ; then
    
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install openssl
    check=$(xcode-select -p)
    if [[ $check == 2 ]] ; then
        xcode-select --install
    fi
    cd ~/Downloads || return
    curl -O http://ftp.gnu.org/gnu/wget/wget-1.15.tar.gz
    tar xvzf wget-1.15.tar.gz
    cd wget-1.15/
    ./configure --with-ssl=openssl
    make
    sudo make install
    
    brew update
    
fi
echo '$platform'
./Java\ Pod\ Template//VM/install-vm
./Java\ Pod\ Template/libs/install-libs
